services:
    email.email:
        class: Librinfo\EmailBundle\Admin\EmailAdminConcrete
        arguments: [~, Librinfo\EmailBundle\Entity\Email, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Email }
        calls:
            - [ setTemplate, [edit, LibrinfoEmailBundle:CRUD:email_edit.html.twig]]