parameters:
    librinfo:
######  Email ##########
        Librinfo\EmailBundle\Entity\Email:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            field_from:
                                type: text
                            field_to:
                                type: text
                            field_subject:
                                type: text
                            content:
                                type: textarea
                                attr:
                                    class: tinymce
                                    data-theme: advanced
                            textContent:
                                type: text
                                required: false
                        form_group_attachments:
                            attachments:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    delete: true
                                    btn_delete: true
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    inline: table
                                    allow_delete: true
                        form_group_test:
                            isTest:
                                type: checkbox
                                required: false
                            testAdress:
                                type: text
                                required: false
                    _options:
                        tabsOrder: [form_group_general, form_group_specifics]
                        groupsOrder: ['', attachments]
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    field_to: ~
                    field_subject: ~
                    sent: ~
                    _action:
                        type: actions
                        _options:
                            actions:
                                send:
                                    template: LibrinfoEmailBundle:CRUD:list__action_send.html.twig
                    _options:
                        fieldsOrder:
                            - field_from
                            - field_to
                            - field_subject
                    _export_format:
                        csv: [ field_from, field_to, field_subject, field_cc, field_bcc, textContent, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    field_from: ~
                    field_to: ~
                    field_subject: ~
                    content: ~
                    textContent: ~
                    sent: ~
                    _options:
                        fieldsOrder:
                            - field_to
                            - field_subject

###### EmailAttachment  ############
        Librinfo\EmailBundle\Entity\EmailAttachment:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Datagrid\ListMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            file:
                                type: file
                                required: false
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
                    mimeType: ~
                    size: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~
                    mimeType: ~
