parameters:
    librinfo:
        configuration:
            templates:
                show:
                    stats: LibrinfoEmailBundle:CRUD:show_field_stats.html.twig
######  Email ##########
        Librinfo\EmailBundle\Entity\Email:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                   default:
                        form_group_general:
                            field_to: ~
                            field_cc: ~
                            field_bcc: ~
                            
                            textContent:
                                type: textarea
                                label: Content
                        form_group_attachments:
                            attachments: ~
                        form_group_tracking:
                            stats:
                                type: stats
                        _options:
                            groupsOrder:
                            - form_group_general
                            - form_group_tracking
                            - form_group_attachments
                            - from_group_misc
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            field_from:
                                type: text
                            field_to:
                                type: text
                            field_subject:
                                type: text
                                required: false
                            field_cc:
                                type: text
                                required: false
                            field_bcc:
                                type: text
                                required: false
                            template:
                                attr:
                                    class: template_select
                            content:
                                type: textarea
                                attr:
                                    class: tinymce
                                    data-theme: advanced
                        form_group_attachments:
                            attachments:
                                type: dropzone
                                required: false
                        form_group_template:
                            isTemplate:
                                type: checkbox
                                required: false
                            newTemplateName:
                                type: text
                                required: false
                            isTest:
                                type: checkbox
                                required: false
                                attr:
                                    class: is_test
                            testAddress:
                                type: text
                                required: false
                            tracking:
                                type: checkbox
                                required: false
                    _options:
                        tabsOrder: [ form_group_general, form_group_specifics ]
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    chartist: ~
                        
                    field_to: ~
                    field_subject: ~
                    sent: ~
                    _actions:
                        type: actions
                        label: Action
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
                            send:
                                template: LibrinfoEmailBundle:CRUD:list__action_send.html.twig
                            duplicate:
                                template: LibrinfoEmailBundle:CRUD:list__action_duplicate.html.twig
                    _options:
                        fieldsOrder:
                            - field_to
                            - field_subject
                            - sent
                    _export_format:
                        csv: [ field_from, field_to, field_subject, field_cc, field_bcc, textContent, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    field_from: ~
                    field_to: ~
                    field_subject: ~
                    content: ~
                    textContent: ~
                    sent: ~
                    _options:
                        fieldsOrder:
                            - field_to
                            - field_subject
                    
########## EmailTemplate ##########
        Librinfo\EmailBundle\Entity\EmailTemplate:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            name:
                                type: text
                            content:
                                type: textarea
                                attr:
                                    class: tinymce
                                    data-theme: advanced
                    _options:
                            tabsOrder: [form_group_general, form_group_specifics]
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    name: ~
                    content: ~