parameters:
    librinfo:
######  Email ##########
        Librinfo\EmailBundle\Entity\Email:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            field_from:
                                type: text
                            field_to:
                                type: text
                            field_subject:
                                type: text
                            content:
                                type: textarea
                                attr:
                                    class: tinymce
                                    data-theme: advanced
                            textContent:
                                type: text
                        form_group_attachments:
                            attachments:
                                type: sonata_type_collection
                                by_reference: false
                                type_options:
                                    required: false
                                    delete: true
                                    btn_delete: true
                                required: false
                                label: false
                                _options:
                                    edit: inline
                                    inline: table
                                    allow_delete: true
                    _options:
                        tabsOrder: [form_group_general, form_group_specifics]
                        groupsOrder: ['', attachments]
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    field_from: ~
                    field_to: ~
                    field_subject: ~
                    _options:
                        fieldsOrder:
                            - field_from
                            - field_to
                            - field_subject
                    _export_format:
                        csv: [ field_from, field_to, field_subject, field_cc, field_bcc, textContent, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    field_from: ~
                    field_to: ~
                    field_subject: ~
                    content: ~
                    textContent: ~
                    sent: ~
                    _options:
                        fieldsOrder:
                            - field_to
                            - field_subject

###### EmailAttachment  ############
        Librinfo\EmailBundle\Entity\EmailAttachment:
              Sonata\AdminBundle\Show\ShowMapper:
                  _copy: Sonata\AdminBundle\Form\FormMapper
              Sonata\AdminBundle\Form\FormMapper:
                  add:
                      form_group_general:
                          '':
                              name: ~
                              mimeType: ~
                              size: ~
                              file:
                                  type: file
                                  required: false
              Sonata\AdminBundle\Datagrid\ListMapper:
                  add:
                      name: ~
                      mimeType: ~
                      size: ~
              Sonata\AdminBundle\Datagrid\DatagridMapper:
                  add:
                      name: ~
                      mimeType: ~
