parameters:
    librinfo:
######  Email ##########
        Librinfo\EmailBundle\Entity\Email:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            field_from:
                                type: text
                            field_to:
                                type: text
                            field_subject:
                                type: text
                            template:
                                attr:
                                    class: template_select
                            content:
                                type: textarea
                                attr:
                                    class: tinymce
                                    data-theme: advanced
                        form_group_attachments:
                            attachments:
                                type: dropzone
                                required: false
                                attr:
                                    class: dropzone
                        form_group_template:
                            isTemplate:
                                type: checkbox
                                required: false
                            newTemplateName:
                                type: text
                                required: false
                        form_group_test:
                            isTest:
                                type: checkbox
                                required: false
                                attr:
                                    class: is_test
                            testAdress:
                                type: text
                                required: false
                        form_group_tracking:
                            tracking:
                                type: checkbox
                                required: false
                    _options:
                        tabsOrder: [form_group_general, form_group_specifics]
                        groupsOrder: ['', attachments]
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    field_to: ~
                    field_subject: ~
                    sent: ~
                    _action:
                        type: actions
                        _options:
                            actions:
                                send:
                                    template: LibrinfoEmailBundle:CRUD:list__action_send.html.twig
                    _options:
                        fieldsOrder:
                            - field_from
                            - field_to
                            - field_subject
                    _export_format:
                        csv: [ field_from, field_to, field_subject, field_cc, field_bcc, textContent, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    field_from: ~
                    field_to: ~
                    field_subject: ~
                    content: ~
                    textContent: ~
                    sent: ~
                    _options:
                        fieldsOrder:
                            - field_to
                            - field_subject

###### EmailAttachment  ############
        Librinfo\EmailBundle\Entity\EmailAttachment:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Datagrid\ListMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            file:
                                type: file
                                required: false
                                data_class: null
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
                    mimeType: ~
                    size: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~
                    mimeType: ~
                    
########## EmailTemplate ##########
        Librinfo\EmailBundle\Entity\EmailTemplate:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            name:
                                type: text
                            content:
                                type: textarea
                                attr:
                                    class: tinymce
                                    data-theme: advanced
                    _options:
                            tabsOrder: [form_group_general, form_group_specifics]
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    name: ~
                    content: ~

########## EmailReceipt ##########
        Librinfo\EmailBundle\Entity\EmailReceipt:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            address: ~
                            date: ~
                    _options:
                            tabsOrder: [form_group_general, form_group_specifics]
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    address: ~
                    date: ~
                    
########## EmailLink ##########
        Librinfo\EmailBundle\Entity\EmailLink:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            destination: ~
                            address: ~
                            date: ~
                    _options:
                            tabsOrder: [form_group_general, form_group_specifics]
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    destination: ~
                    address: ~
                    date: